# Generated by Django 2.2.6 on 2020-02-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=50)),
                ('release', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=50)),
                ('transmission_name', models.SmallIntegerField(choices=[(1, 'Механика'), (2, 'Автомат'), (3, 'Робот')], default='1')),
                ('color', models.CharField(max_length=50)),
            ],
        ),
    ]
